debug: false
token: http://xmq0y.mjt.lu/lnk/AMQAANHtDwkAAAAAAAAAAKA0ATUAAYCrZvYAAAAAAA8pmABjFyLlmCwdvg-SRyeRt6CqudxTHwAO85E/2/iHB14zFSZ0Yu4gqBo0tHLA/aHR0cHM6Ly9hcHAua295ZWIuY29tL2FjY291bnQvdmFsaWRhdGUvZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxlSEFpT2pFNE1qQXlNamN3TkRBc0ltcDBhU0k2SWpjNFltRTJaak5pTFRBelpqQXROREkzTVMxaE1tSTNMVGcwTWpoa01XUTBNVEE0TnlKOS5pQWpDbEhDT2FEYVZ0V2JuQ1lGRTFNUkotZEtUdncwMHV4bDVIR1FLY1Y4
url: https://app.koyeb.com
